### ISSUE TITLE
Failing TPC kernel tests on simulator

### ISSUE THREAD

**Issue by XianFuWongIntel** [HabanaAI/Habana_Custom_Kernel#15]
Hi there,

I have followed the guides to [build](https://github.com/HabanaAI/Habana_Custom_Kernel/tree/9363a1f7daba005e23231c45435f78060eb555ad#build-the-template-examples) and  [run ](https://docs.habana.ai/en/latest/TPC/TPC_Debugger/Start_Debug_Session.html?highlight=tpc_kernel_tests#manually-run-the-tpc-test-program) the TPC kernel tests on simulator, managed to compile and run it but none of the tests are passed. E.g. `FilterFwd2DBF16Test`

![image](https://user-images.githubusercontent.com/8991906/196092795-3b1d7941-acf8-49f9-a482-91b29137189d.png)

As well as `Segmentation fault` for some tests. E.g. `CastF16toI16Gaudi2Test`

![image](https://user-images.githubusercontent.com/8991906/196093887-eda4bb99-637e-4ea8-9bf2-394f3c422d8a.png)

Any advice or suggestion? 
Thank you!

Tested on:
- OS: Ubuntu 20.04.4 LTS (Docker container)
- habanatools: 1.6.1-92 (installed from [here](https://vault.habana.ai/ui/repos/tree/General/debian/focal/pool/main/h/habanatools/habanatools_1.6.1-92_amd64.deb))
- Commit# : 9363a1f7daba005e23231c45435f78060eb555ad (branch `main`)

cc: @vuiseng9

**Comment by ssarkar2** [comment]
Please see response [here](https://forum.habana.ai/t/failing-tpc-kernel-tests-on-simulator/326)

**Comment by XianFuWongIntel** [comment]
Resolved with older version of `habanatools` and codebase:
- habanatools: 1.4.1-11 (installed from [here](https://vault.habana.ai/ui/repos/tree/General/debian/bionic/pool/main/h/habanatools/habanatools_1.4.1-11_amd64.deb))
- Commit#: 7327f98e8182d634d81396ca482357a2f8c3deb5 (branch `1.4`)
